import dotenv from "dotenv";
dotenv.config();

import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 465,
  secure: true, // SSL
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});


transporter.verify((error, success) => {
  if (error) {
    console.error("❌ SMTP Verification Failed");
    console.error(error);
  } else {
    console.log("✅ Gmail SMTP Connected");
  }
});

export async function sendReportEmail(email, report) {
  try {
    const info = await transporter.sendMail({
      from: `"Prapti AI" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: "Your Prapti AI Financial Report",
      html: `
        <div style="font-family:Arial,sans-serif;max-width:650px;margin:auto;padding:20px;border:1px solid #ddd;border-radius:10px">
          <h2 style="color:#2563eb;">📊 Prapti AI Financial Report</h2>

          <table style="width:100%;border-collapse:collapse">
            <tr>
              <td><b>Loan Amount</b></td>
              <td>₹${Number(report.loanAmount).toLocaleString("en-IN")}</td>
            </tr>

            <tr>
              <td><b>Interest Rate</b></td>
              <td>${report.interestRate}%</td>
            </tr>

            <tr>
              <td><b>Loan Tenure</b></td>
              <td>${report.tenure} Years</td>
            </tr>

            <tr>
              <td><b>Monthly EMI</b></td>
              <td>₹${Number(report.emi).toLocaleString("en-IN")}</td>
            </tr>

            <tr>
              <td><b>Health Score</b></td>
              <td>${report.healthScore}/100</td>
            </tr>
          </table>

          <hr>

          <h3>🤖 AI Recommendation</h3>

          <pre style="white-space:pre-wrap;font-family:Arial,sans-serif;">
${report.recommendation}
          </pre>

          <hr>

          <p style="font-size:13px;color:#666">
            Generated by <b>Prapti AI</b>
          </p>
        </div>
      `,
    });

    console.log("✅ Email Sent:", info.messageId);

    return info;
  } catch (error) {
    console.error("❌ Email Error:");
    console.error(error);
    throw error;
  }
}