import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    question: "How does Prapti AI calculate financial risk?",
    answer:
      "Prapti AI analyzes income, existing debt, loan tenure, EMI burden and repayment patterns to estimate your overall financial risk.",
  },
  {
    question: "Is my financial information secure?",
    answer:
      "Yes. Your data is processed securely and is never shared with third parties. Sensitive information remains protected throughout analysis.",
  },
  {
    question: "Can I compare multiple loan options?",
    answer:
      "Yes. Compare different loan amounts, interest rates and repayment durations side-by-side before making a decision.",
  },
  {
    question: "Are the recommendations generated by AI?",
    answer:
      "Yes. Our AI engine evaluates repayment strategies, investment opportunities and debt reduction techniques to provide personalized insights.",
  },
];

export default function FAQ() {
  const [active, setActive] = useState(0);

  return (
    <section className="border-t border-gray-200 bg-white">
      <div className="max-w-5xl mx-auto px-6 py-24">

        <p className="text-xs uppercase tracking-[0.3em] text-blue-600">
          Frequently Asked Questions
        </p>

        <h2 className="mt-4 text-4xl font-semibold text-gray-900">
          Everything you need to know.
        </h2>

        <div className="mt-14 space-y-4">

          {faqs.map((faq, index) => (
            <div
              key={index}
              className="border border-gray-200 bg-white"
            >
              <button
                onClick={() =>
                  setActive(active === index ? -1 : index)
                }
                className="flex w-full items-center justify-between p-5 text-left"
              >
                <span className="font-medium text-gray-800">
                  {faq.question}
                </span>

                <ChevronDown
                  className={`h-5 w-5 transition-transform ${
                    active === index ? "rotate-180" : ""
                  }`}
                />
              </button>

              {active === index && (
                <div className="border-t border-gray-200 px-5 py-5 text-sm leading-7 text-gray-600">
                  {faq.answer}
                </div>
              )}
            </div>
          ))}

        </div>

      </div>
    </section>
  );
}