import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const faqs = [
  {
    question: "How does Prapti AI calculate financial risk?",
    answer:
      "Prapti AI analyzes income, existing debt, loan tenure, EMI burden, repayment patterns, and financial commitments to estimate your overall financial risk.",
  },
  {
    question: "Is my financial information secure?",
    answer:
      "Yes. Your financial information is securely processed and never shared with third parties. All sensitive data remains protected throughout the analysis process.",
  },
  {
    question: "Can I compare multiple loan options?",
    answer:
      "Absolutely. Compare different loan amounts, repayment periods, interest rates, and total borrowing costs before making any financial decision.",
  },
  {
    question: "Are the recommendations generated by AI?",
    answer:
      "Yes. Prapti AI evaluates your financial profile using intelligent algorithms to provide personalized recommendations on loans, investments, savings, and repayment strategies.",
  },
];

export default function FAQ() {
  const [active, setActive] = useState(0);

  return (
    <section
      id="faq"
      className="border-t border-gray-200 bg-white"
    >
      <div
        className="
          mx-auto
          max-w-5xl
          px-5
          py-14

          sm:px-6
          sm:py-16

          lg:px-8
          lg:py-24
        "
      >
        {/* Heading */}

        <div className="max-w-3xl">

          <p
            className="
              text-[11px]
              uppercase
              tracking-[0.3em]
              text-blue-600
            "
          >
            Frequently Asked Questions
          </p>

          <h2
            className="
              mt-4
              text-3xl
              font-semibold
              leading-tight
              text-gray-900

              sm:text-4xl

              lg:text-5xl
            "
          >
            Everything you need to know.
          </h2>

          <p
            className="
              mt-6
              text-base
              leading-8
              text-gray-600
            "
          >
            Answers to the most common questions about
            financial analysis, security, AI recommendations,
            and using Prapti AI effectively.
          </p>

        </div>

        {/* FAQ */}

        <div className="mt-14 space-y-5">

          {faqs.map((faq, index) => (

            <motion.div

              key={index}

              layout

              className="
                border
                border-gray-200
                bg-white
                shadow-sm
                transition-all
                duration-300
                hover:border-blue-300
              "

            >

              <button

                onClick={() =>
                  setActive(active === index ? -1 : index)
                }

                className="
                  flex
                  w-full
                  items-center
                  justify-between
                  gap-5
                  p-5

                  sm:p-6
                "

              >

                <span
                  className="
                    text-left
                    text-base
                    font-semibold
                    text-gray-900

                    sm:text-lg
                  "
                >
                  {faq.question}
                </span>

                <ChevronDown
                  size={22}
                  className={`
                    flex-shrink-0
                    transition-transform
                    duration-300

                    ${
                      active === index
                        ? "rotate-180 text-blue-600"
                        : "text-gray-500"
                    }
                  `}
                />

              </button>

              <AnimatePresence>

                {active === index && (

                  <motion.div

                    initial={{
                      opacity: 0,
                      height: 0,
                    }}

                    animate={{
                      opacity: 1,
                      height: "auto",
                    }}

                    exit={{
                      opacity: 0,
                      height: 0,
                    }}

                    transition={{
                      duration: 0.25,
                    }}

                    className="overflow-hidden"

                  >

                    <div
                      className="
                        border-t
                        border-gray-200
                        px-5
                        py-5

                        text-sm
                        leading-8
                        text-gray-600

                        sm:px-6
                        sm:text-base
                      "
                    >

                      {faq.answer}

                    </div>

                  </motion.div>

                )}

              </AnimatePresence>

            </motion.div>

          ))}

        </div>

      </div>
    </section>
  );
}